version: '3.8'

services:
  user-service:
    build: .
    container_name: streamhive-user-service
    env_file:
      - .env
    ports:
      - "8082:8082" # container listens on 8080
    networks:
      - streamhive-net

networks:
  streamhive-net:
    driver: bridge
